### ISSUE TITLE
Issue when deploying and running app.js

### ISSUE THREAD

**Issue by joshlopes** [alexleventer/distelli-slash#4]
```
const endPoint = `https://api.distelli.com/${username}`;
                 ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

when i run on my machine it works fine but not on the deployed server.

Also there are a few things your README is not aware! such disable the build parameters from the APP, and on the blog entry you don't specify the VARIABLES to set on the environment. I still didn't try this cuz the error above. i will probably try to do this deployment manually

Other than that seems a nice project! thanks

**Comment by joshlopes** [comment]
Nvm missed some of stuff! i was using a very old node version, with the recent one is working okay! also i missed some configurations cuz i didnt quite got it right.

**Comment by alexleventer** [comment]
👍
